# Generated by Django 4.1 on 2022-08-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
