# Generated by Django 4.1 on 2022-08-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ekartapp', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descsription',
            new_name='description',
        ),
    ]
